# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .gitignore
    - .editorconfig
    - README.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md
    - LICENSE.txt
    - azure-pipelines-linux.yml
    - azure-pipelines-windows.yml
    - doc
    - samples

pool:
  vmImage: 'windows-2022'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'tools/build.ps1'
