# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .gitignore
    - .editorconfig
    - README.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md
    - LICENSE.txt
    - azure-pipelines-linux.yml
    - azure-pipelines-windows.yml
    - doc
    - samples

pool:
  vmImage: ubuntu-22.04

steps:
- script: sudo apt update && sudo apt upgrade -y
  displayName: 'Ensure the system is up-to-date'

- script: sudo apt update && sudo apt install -y g++ cmake libssl-dev
  displayName: 'Install g++ cmake libssl-dev'

- script: sudo apt install -y dotnet-sdk-7.0
  displayName: 'Install .NET SDK x64 7.0'

- bash: tools/build.sh
  displayName: 'Build Graph Engine'
